apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthapp-deployment
  labels:
    app: healthapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthapp
  template:
    metadata:
      labels:
        app: healthapp
    spec:
      containers:
      - name: healthapp
        image: goapp:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: APP_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: healthapp-config
              key: APP_MESSAGE
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: healthapp-secret
              key: API_KEY
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
---

