FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod ./

RUN go mod download  

COPY . .


RUN go mod tidy

RUN go build -o goapp app.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/goapp .

CMD ["./goapp"]